#!/usr/bin/env python3
"""Copy each diagram card's preview from docs/diagram-types.html into docs/index.html.

docs/index.html shows a hover box for every diagram badge (an element with
data-card="<id>"). The box is filled from <template id="pv-<id>">. This script
builds those templates from the cards in docs/diagram-types.html and rewrites
the block between <!-- previews:start --> and <!-- previews:end --> in index.html.

Each template holds the card title (without its code, e.g. "Container"), the
grey sub-line, the card's <svg> copied exactly, and the "Use when" and
"Not when" lines.

The block also starts with a copy of the catalogue's shared <svg><defs> (the
arrowhead markers). The copied diagrams and the SVGs in index.html point at
those ids with url(#id) or href="#id". The script fails when such a reference
has no matching id, so a missing or renamed marker cannot pass --check.

Usage:
    python docs/tools/sync_previews.py           # rewrite the block
    python docs/tools/sync_previews.py --check   # change nothing; exit 1 when out of date

Python 3.10+, standard library only. Output is UTF-8 with LF line endings.
Running it twice changes nothing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
INDEX = DOCS / "index.html"
CATALOGUE = DOCS / "diagram-types.html"

START = "<!-- previews:start -->"
END = "<!-- previews:end -->"
NOTE = ("<!-- Generated by docs/tools/sync_previews.py from diagram-types.html. "
        "Do not edit by hand: change the card, then run the script. -->")

DATA_CARD = re.compile(r'\bdata-card="([^"]+)"')
COMMENT = re.compile(r"<!--.*?-->", re.S)
CARD_OPEN = re.compile(r'<div class="card" id="([^"]+)">')
DIV_TAG = re.compile(r"<(/?)div\b[^>]*>")
H3 = re.compile(r"<h3>(.*?)</h3>", re.S)
CODE_PREFIX = re.compile(r"^[A-Z]\d+\s*·\s*")
ALT = re.compile(r'<p class="alt">(.*?)</p>', re.S)
SVG = re.compile(r"<svg\b.*?</svg>", re.S)
YES = re.compile(r'<p class="yes">.*?</p>', re.S)
NO = re.compile(r'<p class="no">.*?</p>', re.S)
SHARED_DEFS = re.compile(r"<svg\b[^>]*>\s*<defs>.*?</defs>\s*</svg>", re.S)
# a real template tag only: the CSS comment that mentions <template id="pv-<id>"> must not match
TEMPLATE = re.compile(r'<template id="[^"<>]+">.*?</template>', re.S)
ANY_SVG = re.compile(r"<svg\b.*?</svg>", re.S)
REF = re.compile(r'url\(#([^)\s]+)\)|\bhref="#([^"]+)"')
ID = re.compile(r'\bid="([^"]+)"')


class SyncError(Exception):
    """A problem the user must fix by hand."""


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def cards(catalogue: str) -> dict[str, str]:
    """Return {id: card html} for every <div class="card" id="..."> in the catalogue."""
    found: dict[str, str] = {}
    for m in CARD_OPEN.finditer(catalogue):
        depth = 0
        for tag in DIV_TAG.finditer(catalogue, m.start()):
            depth += -1 if tag.group(1) else 1
            if depth == 0:
                found[m.group(1)] = catalogue[m.start():tag.end()]
                break
        else:
            raise SyncError(f"card {m.group(1)!r} in {CATALOGUE.name} has no closing </div>")
    return found


def part(pattern: re.Pattern[str], card: str, card_id: str, what: str) -> re.Match[str]:
    m = pattern.search(card)
    if not m:
        raise SyncError(f"card {card_id!r} in {CATALOGUE.name} has no {what}")
    return m


def template(card_id: str, card: str) -> str:
    title = CODE_PREFIX.sub("", part(H3, card, card_id, "<h3>").group(1).strip())
    alt = part(ALT, card, card_id, '<p class="alt">').group(1).strip()
    svg = part(SVG, card, card_id, "<svg>").group(0)
    yes = part(YES, card, card_id, '<p class="yes"> ("Use when")').group(0)
    no = part(NO, card, card_id, '<p class="no"> ("Not when")').group(0)
    return (f'<template id="pv-{card_id}">\n'
            f'<p class="pv-t">{title}</p>\n'
            f'<p class="alt">{alt}</p>\n'
            f'{svg}\n'
            f'<div class="when">{yes}\n'
            f'  {no}</div>\n'
            f'</template>')


def shared_defs(catalogue: str, card_html: list[str]) -> str:
    """Return the one <svg><defs> block in the catalogue that sits outside every card."""
    outside = COMMENT.sub("", catalogue)
    for card in card_html:
        outside = outside.replace(card, "")
    found = SHARED_DEFS.findall(outside)
    if len(found) != 1:
        raise SyncError(f"{CATALOGUE.name} needs exactly one shared <svg><defs> block outside "
                        f"the cards; found {len(found)}")
    return found[0]


def svg_refs(html: str) -> set[str]:
    """Return every id that the <svg> elements in html point at with url(#id) or href="#id"."""
    return {a or b for svg in ANY_SVG.findall(html) for a, b in REF.findall(svg)}


def check_refs(page: str) -> None:
    """Raise SyncError when an SVG reference in the page has no matching id.

    Ids inside a <template> are not in the document until the script clones the template.
    So a template may use its own ids and the page ids; the rest of the page uses page ids only.
    """
    page = COMMENT.sub("", page)
    outside = TEMPLATE.sub("", page)
    page_ids = set(ID.findall(outside))
    problems = [f"{INDEX.name} outside the previews: #{ref}"
                for ref in sorted(svg_refs(outside) - page_ids)]
    for t in TEMPLATE.findall(page):
        own = ID.findall(t)
        problems += [f'<template id="{own[0]}">: #{ref}'
                     for ref in sorted(svg_refs(t) - page_ids - set(own))]
    if problems:
        raise SyncError("SVG reference(s) with no matching id. Add the id to the shared <defs> "
                        f"in {CATALOGUE.name}:\n  " + "\n  ".join(problems))


def build(index: str, catalogue: str) -> str:
    """Return index.html with a fresh previews block."""
    if index.count(START) != 1 or index.count(END) != 1:
        raise SyncError(f"{INDEX.name} needs exactly one {START} and one {END}")
    head, rest = index.split(START, 1)
    _, tail = rest.split(END, 1)

    ids = list(dict.fromkeys(DATA_CARD.findall(COMMENT.sub("", head + tail))))
    if not ids:
        raise SyncError(f"{INDEX.name} has no data-card badges")
    all_cards = cards(catalogue)
    missing = [i for i in ids if i not in all_cards]
    if missing:
        raise SyncError(f"data-card id(s) with no card in {CATALOGUE.name}: {', '.join(missing)}")

    order = [i for i in all_cards if i in ids]   # catalogue order: stable output
    defs = shared_defs(catalogue, list(all_cards.values()))
    body = "\n".join([NOTE, defs] + [template(i, all_cards[i]) for i in order])
    page = f"{head}{START}\n{body}\n{END}{tail}"
    check_refs(page)
    return page


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 when the previews block is out of date")
    args = ap.parse_args(argv)

    try:
        current = read(INDEX)
        fresh = build(current, read(CATALOGUE))
    except (OSError, SyncError) as e:
        print(f"sync_previews: {e}", file=sys.stderr)
        return 1

    if args.check:
        if fresh != current:
            print("sync_previews: the hover-box previews in docs/index.html are out of date with "
                  "docs/diagram-types.html.\nRun: python docs/tools/sync_previews.py", file=sys.stderr)
            return 1
        print("sync_previews: previews in sync")
        return 0

    if fresh == current:
        print("sync_previews: previews already in sync")
        return 0
    with INDEX.open("w", encoding="utf-8", newline="\n") as f:
        f.write(fresh)
    print(f"sync_previews: rewrote the previews block in {INDEX.relative_to(DOCS.parent).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
